# -*- coding: utf-8 -*-
"""Docker simple code for sql appliaction

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4aA_Er1NADZro7ynIVajVXTzI8M-zcA
"""

# version: '3.3'

# services:
#   nsql_app_3:
#     build: ./
#     command: python3 app.py
#     ports:
#       - 9385:9385
#     hostname: nsql_app_3
#     restart: always
#     container_name: nsql_app_3